name: npm login

description: Configures npm to use a registry with a given scope

inputs:
  protocol:
    required: false
    default: https
  scope:
    required: false
  registry:
    required: false
  username:
    required: false
  email:
    required: false
  password:
    required: false

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        echo "::info::NOTE: This action is deprecated and is no longer maintained."
        echo "::info::Please, migrate to https://github.com/actions/setup-node"

    - env:
        INPUT_EMAIL: ${{ inputs.email }}
        INPUT_PASSWORD: ${{ inputs.password }}
        INPUT_PROTOCOL: ${{ inputs.protocol }}
        INPUT_REGISTRY: ${{ inputs.registry }}
        INPUT_SCOPE: ${{ inputs.scope }}
        INPUT_USERNAME: ${{ inputs.username }}
      run: ${{ github.action_path }}/npm-login.sh
      shell: bash
